### ISSUE TITLE
Please update Composer / Packagist package

### ISSUE THREAD

**Issue by discotroy** [cebe/markdown-latex#9]
I've recently started using this software, and it's awesome, thank you very much for publishing it.  

The v1.0.0 package accessible via Composer was created a few days before you added an important commit to this repo - to allow \escaping and use of LaTeX commands.  Is there any chance you could push a new version to Packagist, please?

Many thanks.

**Comment by cebe** [comment]
just tagged a 1.1.0 release. sorry for letting you wait so long, I was not aware that anything important was comitted on master.
